resove deps

diff --git a/22-uprobe/Makefile b/22-uprobe/Makefile
--- a/22-uprobe/Makefile
+++ b/22-uprobe/Makefile
@@ -1,96 +1,130 @@
-BASEDIR = $(abspath ../../)
+OUTPUT = ./output
+LIBBPF = ../libbpf
 
-OUTPUT = ../../output
-
-LIBBPF_SRC = $(abspath ../../libbpf/src)
+LIBBPF_SRC = $(abspath $(LIBBPF)/src)
 LIBBPF_OBJ = $(abspath $(OUTPUT)/libbpf.a)
 
 CC = gcc
 CLANG = clang
-GO = go
 
-CFLAGS = -g -O2 -Wall -fpie
+ARCH := $(shell uname -m)
+ARCH := $(subst x86_64,amd64,$(ARCH))
+GOARCH := $(ARCH)
+
+BPFTOOL = $(shell which bpftool || /bin/false)
+BTFFILE = /sys/kernel/btf/vmlinux
+DBGVMLINUX = /usr/lib/debug/boot/vmlinux-$(shell uname -r)
+GIT = $(shell which git || /bin/false)
+VMLINUXH = vmlinux.h
+
+# libbpf
+
+LIBBPF_OBJDIR = $(abspath ./$(OUTPUT)/libbpf)
+LIBBPF_DESTDIR = $(abspath ./$(OUTPUT))
+
+CFLAGS = -ggdb -gdwarf -O2 -Wall -fpie -Wno-unused-variable -Wno-unused-function
 LDFLAGS =
-ARCH := $(shell uname -m | sed 's/x86_64/amd64/g; s/aarch64/arm64/g')
+
+BPF_CFLAGS_STATIC = "-I$(abspath $(OUTPUT))"
+BPF_LDFLAGS_STATIC = "-lelf -lz $(LIBBPF_OBJ)"
 
 CGO_CFLAGS_STATIC = "-I$(abspath $(OUTPUT))"
 CGO_LDFLAGS_STATIC = "-lelf -lz $(LIBBPF_OBJ)"
+CGO_EXTLDFLAGS_STATIC = '-w -extldflags "-static"'
 
-CGO_CFLAGS_DYN = "-I. -I/usr/include/"
+CGO_CFGLAGS_DYN = "-I. -I/usr/include/"
 CGO_LDFLAGS_DYN = "-lelf -lz -lbpf"
+CGO_EXTLDFLAGS_DYN = '-w'
 
-.PHONY: $(TEST)
-.PHONY: $(TEST).go
-.PHONY: $(TEST).bpf.c
+## program
 
-TEST = main
+.PHONY: $(PROGRAM)
+.PHONY: $(PROGRAM).bpf.c
 
-all: $(TEST)-static
+PROGRAM = main
 
-.PHONY: libbpfgo
-.PHONY: libbpfgo-static
-.PHONY: libbpfgo-dynamic
+all:
+	$(MAKE) -C . $(PROGRAM)
 
-## libbpfgo
+# vmlinux header file
 
-libbpfgo-static:
-	$(MAKE) -C $(BASEDIR) libbpfgo-static
+.PHONY: vmlinuxh
+vmlinuxh: $(VMLINUXH)
 
-libbpfgo-dynamic:
-	$(MAKE) -C $(BASEDIR) libbpfgo-dynamic
-
-vmlinuxh:
-	$(MAKE) -C $(BASEDIR) vmlinuxh
-
-## test (bpf)
-
-.PHONY: $(TEST)-bpf
-
-$(TEST)-bpf: vmlinuxh
-	$(CLANG) $(CFLAGS) -target bpf -D__TARGET_ARCH_$(ARCH) -I$(OUTPUT) -c $(TEST).bpf.c -o $(TEST).bpf.o
-
-## test deps
-
-DEPS = ctest gotest
-
-.PHONY: ctest
-ctest:
-	@if [ ! -x ctest ]; then \
-		$(CLANG) -o ctest test.c; \
+$(VMLINUXH): $(OUTPUT)
+ifeq ($(wildcard $(BPFTOOL)),)
+	@echo "ERROR: could not find bpftool"
+	@exit 1
+endif
+	@if [ -f $(DBGVMLINUX) ]; then \
+		echo "INFO: found dbg kernel, generating $(VMLINUXH) from $(DBGVMLINUX)"; \
+		$(BPFTOOL) btf dump file $(DBGVMLINUX) format c > $(VMLINUXH); \
+	fi
+	@if [ ! -f $(BTFFILE) ] && [ ! -f $(DBGVMLINUX) ]; then \
+		echo "ERROR: kernel does not seem to support BTF"; \
+		exit 1; \
+	fi
+	@if [ ! -f $(VMLINUXH) ]; then \
+		echo "INFO: generating $(VMLINUXH) from $(BTFFILE)"; \
+		$(BPFTOOL) btf dump file $(BTFFILE) format c > $(VMLINUXH); \
 	fi
 
-.PHONY: gotest
-gotest:
-	@if [ ! -x gotest ]; then \
-		$(GO) build -o gotest test.go; \
-	 fi
+# static libbpf generation for the git submodule
 
-## test
+.PHONY: libbpf
+libbpf: $(LIBBPF_OBJ)
 
-.PHONY: $(TEST)-static
-.PHONY: $(TEST)-dynamic
+$(LIBBPF_OBJ): $(LIBBPF_SRC) $(wildcard $(LIBBPF_SRC)/*.[ch]) | $(OUTPUT)/libbpf
+	CC="$(CC)" CFLAGS="$(CFLAGS)" LD_FLAGS="$(LDFLAGS)" \
+	   $(MAKE) -C $(LIBBPF_SRC) \
+		BUILD_STATIC_ONLY=1 \
+		OBJDIR=$(LIBBPF_OBJDIR) \
+		DESTDIR=$(LIBBPF_DESTDIR) \
+		INCLUDEDIR= LIBDIR= UAPIDIR= prefix= libdir= install
 
-$(TEST)-static: $(TEST)-bpf libbpfgo-static $(DEPS)
-	CC=$(CLANG) CGO_CFLAGS=$(CGO_CFLAGS_STATIC) CGO_LDFLAGS=$(CGO_LDFLAGS_STATIC) \
-	   $(GO) build -o $(TEST)-static ./$(TEST).go
+$(LIBBPF_SRC):
+ifeq ($(wildcard $@), )
+	echo "INFO: updating submodule 'libbpf'"
+	$(GIT) submodule update --init --recursive
+endif
 
-$(TEST)-dynamic: $(TEST)-bpf libbpfgo-dynamic $(DEPS)
-	CC=$(CLANG) CGO_CFLAGS=$(CGO_CFLAGS_DYN) CGO_LDFLAGS=$(CGO_LDFLAGS_DYN) \
-	   $(GO) build -o ./$(TEST)-dynamic ./$(TEST).go
+# output dir
 
-## run
+$(OUTPUT):
+	mkdir -p $(OUTPUT)
 
-.PHONY: run
-.PHONY: run-static
-.PHONY: run-dynamic
+$(OUTPUT)/libbpf:
+	mkdir -p $(OUTPUT)/libbpf
 
-run: run-static
+## program bpf dependency
 
-run-static: $(TEST)-static
-	sudo ./run.sh $(TEST)-static
+$(PROGRAM).bpf.o: $(PROGRAM).bpf.c | vmlinuxh
+	$(CLANG) $(CFLAGS) -target bpf -D__TARGET_ARCH_x86 -I. -I$(OUTPUT) -c $< -o $@
 
-run-dynamic: $(TEST)-dynamic
-	sudo ./run.sh $(TEST)-dynamic
+## GO example
 
+.PHONY: $(PROGRAM)
+
+$(PROGRAM): libbpf | $(PROGRAM).bpf.o
+	CC=$(CLANG) \
+		CGO_CFLAGS=$(CGO_CFLAGS_STATIC) \
+		CGO_LDFLAGS=$(CGO_LDFLAGS_STATIC) \
+                GOARCH=$(GOARCH) \
+                go build \
+                -tags netgo -ldflags $(CGO_EXTLDFLAGS_STATIC) \
+                -o $(PROGRAM) ./$(PROGRAM).go
+
+.PHONE: run
+run:
+	sudo ./main
+
+
+## clean
+
+.PHONY: clean
 clean:
-	rm -f *.o $(TEST)-static $(TEST)-dynamic $(DEPS)
+	$(MAKE) -C $(LIBBPF_SRC) clean
+	rm -rf $(OUTPUT)
+	rm -rf $(VMLINUXH)
+	rm -rf $(PROGRAM) $(PROGRAM)-*static $(PROGRAM)-*dynamic
+	rm -rf $(PROGRAM).bpf.o $(PROGRAM).o
